stages:
  -
    pipeline: Pipeline\Fallback
    stages:
      klevuImage:
        stages:
          - pipeline: Stage\Extract
            args:
              extraction: currentProduct::getKlevuImage()
          - pipeline: Stage\Validate
            args:
              validation: IsNotEqualTo("no_selection")|IsNotEmpty
      image:
        stages:
          - pipeline: Stage\Extract
            args:
              extraction: currentProduct::getImage()
          - pipeline: Stage\Validate
            args:
              validation: IsNotEqualTo("no_selection")|IsNotEmpty
      placeholder:
        stages:
          - pipeline: Stage\Extract
            args:
              extraction: config::getForCurrentStore().placeholder_image
          - pipeline: Stage\Validate
            args:
              validation: IsNotEqualTo("no_selection")|IsNotEmpty
      default:
        stages:
          - pipeline: Stage\StaticValue
            args:
              value: null
  -
    pipeline: Stage\RegisterContext
    args:
      contextKey: "productImage"
  -
    pipeline: Pipeline\Fallback
    stages:
      imageGeneration:
        stages:
          - pipeline: Stage\Extract
            args:
              extraction: productImage::
          - pipeline: Stage\Validate
            args:
              validation: IsNotEmpty
          - pipeline: Pipeline\CreateRecord
            stages:
              - pipeline: Pipeline\CreateRecord
                stages:
                  url:
                    pipeline: Stage\Extract
                    args:
                      extraction: productImage::
                      transformations:
                        - ResizeImage("klevu_image", $config::getForCurrentStore().image_width, $config::getForCurrentStore().image_height, $store::getForCurrentStore().store_id)
                        - Prepend($store::getForCurrentStore().media_url)
                  type:
                    pipeline: Stage\StaticValue
                    args:
                      value: "default"
                  width:
                    pipeline: Stage\Extract
                    args:
                      extraction: config::getForCurrentStore().image_width
                  height:
                    pipeline: Stage\Extract
                    args:
                      extraction: config::getForCurrentStore().image_height
      default:
        stages:
          - pipeline: Stage\StaticValue
            args:
              value: null
