pipeline: Pipeline\CreateRecord
stages:
  default:
    stages:
      -
        pipeline: Stage\Extract
        args:
          extraction: currentProduct::getShortDescription()
          transformations:
            - StripTags(null, ["script"])
            - EscapeHtml
