pipeline: Pipeline\CreateRecord
stages:
  values:
    stages:
      createRecord:
        pipeline: Pipeline\CreateRecord
        stages:
          - pipeline: Stage\Extract
            args:
              extraction: currentParentProduct::getEntityId()
              transformations: ToString
