stages:
  registerMinPriceProduct:
    stages:
      extractMinPrice:
        pipeline: Stage\Extract
        args:
          extraction: currentProduct::
          transformations: ToMinPriceProduct()
      registerMinPrice:
        pipeline: Stage\RegisterContext
        args:
          contextKey: "minPriceProduct"
  processPrices:
    pipeline: Pipeline\CreateRecord
    stages:
      -
        pipeline: Pipeline\CreateRecord
        stages:
          amount:
            pipeline: Pipeline\Fallback
            stages:
              getPrice:
                stages:
                  - pipeline: Stage\Extract
                    args:
                      extraction: minPriceProduct::
                  - pipeline: Stage\Validate
                    args:
                      validation: IsNotEmpty
                  - pipeline: Stage\Extract
                    args:
                      extraction: minPriceProduct::getPrice()
                      transformations:
                        - FormatNumber("2",".")
                        - ToFloat
              defaultPrice:
                pipeline: Stage\StaticValue
                args:
                  value: 0.00
          type:
            pipeline: Stage\StaticValue
            args:
              value: "defaultPrice"
          currency:
            pipeline: Stage\Extract
            args:
              extraction: store::getForCurrentStore().base_currency_code
      -
        pipeline: Pipeline\CreateRecord
        stages:
          amount:
            pipeline: Pipeline\Fallback
            stages:
              getFinalPrice:
                stages:
                  - pipeline: Stage\Extract
                    args:
                      extraction: minPriceProduct::
                  - pipeline: Stage\Validate
                    args:
                      validation: IsNotEmpty
                  - pipeline: Stage\Extract
                    args:
                      extraction: minPriceProduct::getFinalPrice()
                      transformations:
                        - FormatNumber("2",".")
                        - ToFloat
              defaultFinalPrice:
                pipeline: Stage\StaticValue
                args:
                  value: 0.00
          type:
            pipeline: Stage\StaticValue
            args:
              value: "salePrice"
          currency:
            pipeline: Stage\Extract
            args:
              extraction: store::getForCurrentStore().base_currency_code
