pipeline: Pipeline\CreateRecord
stages:
  values:
    pipeline: Stage\Extract
    args:
      extraction: currentProduct::
      transformations:
        - ToCategoryIds
        - Prepend("categoryid_")
