pipeline: Pipeline\CreateRecord
stages:
  default:
    stages:
      getDefaultLanguageValue:
        pipeline: Stage\Extract
        args:
          extraction: currentProduct::getDescription()
          transformations:
            - StripTags(null, ["script"])
            - EscapeHtml
            - Trim
