stages:
  findImageToUse:
    pipeline: Pipeline\Fallback
    stages:
      klevuImage:
        stages:
          getImage:
            pipeline: Stage\Extract
            args:
              extraction: currentProduct::getKlevuImage()
          validateImage:
            pipeline: Stage\Validate
            args:
              validation: IsNotEqualTo("no_selection")|IsNotEmpty
      image:
        stages:
          getImage:
            pipeline: Stage\Extract
            args:
              extraction: currentProduct::getImage()
          validateImage:
            pipeline: Stage\Validate
            args:
              validation: IsNotEqualTo("no_selection")|IsNotEmpty
      placeholder:
        stages:
          getImage:
            pipeline: Stage\Extract
            args:
              extraction: config::getForCurrentStore().placeholder_image
          validateImage:
            pipeline: Stage\Validate
            args:
              validation: IsNotEqualTo("no_selection")|IsNotEmpty
      default:
        stages:
          getImage:
            pipeline: Stage\StaticValue
            args:
              value: null
  registerImage:
    pipeline: Stage\RegisterContext
    args:
      contextKey: "productImage"
  fallbackImageCreation:
    pipeline: Pipeline\Fallback
    stages:
      generateImage:
        stages:
          getImage:
            pipeline: Stage\Extract
            args:
              extraction: productImage::
          validateImage:
            pipeline: Stage\Validate
            args:
              validation: IsNotEmpty
          createRecord:
            pipeline: Pipeline\CreateRecord
            stages:
              default:
                stages:
                  - pipeline: Pipeline\CreateRecord
                    stages:
                      url:
                        pipeline: Stage\Extract
                        args:
                          extraction: productImage::
                          transformations:
                            - ResizeImage("klevu_image", $config::getForCurrentStore().image_width, $config::getForCurrentStore().image_height, $store::getForCurrentStore().store_id)
                            - Prepend($store::getForCurrentStore().media_url)
                      width:
                        pipeline: Stage\Extract
                        args:
                          extraction: config::getForCurrentStore().image_width
                      height:
                        pipeline: Stage\Extract
                        args:
                          extraction: config::getForCurrentStore().image_height
      default:
        stages:
          createRecord:
            pipeline: Stage\StaticValue
            args:
              value: null
