pipeline: Pipeline\CreateRecord
stages:
  $store::getForCurrentStore().base_currency_code:
    pipeline: Pipeline\CreateRecord
    stages:
      defaultPrice:
        stages:
          getPrice:
            pipeline: Stage\Extract
            args:
              extraction: currentProduct::getPrice()
              transformations:
                - ToPriceIncludingTax($currentProduct::, null)
                - FormatNumber("2",".","")
                - ToFloat
      salePrice:
        stages:
          getPrice:
            pipeline: Stage\Extract
            args:
              extraction: currentProduct::
              transformations:
                - ToFinalPrice(1)
                - ToPriceIncludingTax($currentProduct::, null)
                - FormatNumber("2",".","")
                - ToFloat
