pipeline: Pipeline\CreateRecord
stages:
  default:
    stages:
      getDefaultLanguageValue:
        pipeline: Stage\Extract
        args:
          extraction: currentProduct::getShortDescription()
          transformations:
            - StripTags(["p", "br", "hr", "h1", "h2", "h3", "h4", "h5", "h6", "strong", "em", "ul", "ol", "li", "dl", "dt", "dd", "img", "sub", "sup", "small"], ["script"])
            - EscapeHtml
            - Trim
