pipeline: Pipeline\CreateRecord
stages:
  id:
    pipeline: Stage\Extract
    args:
      extraction: currentProduct::getEntityId()
      transformations: ToString
  type:
    pipeline: Stage\StaticValue
    args:
      value: "KLEVU_PARENT_PRODUCT"
  relations:
    pipeline: Pipeline\CreateRecord
    stages:
      categories:
        import: Klevu_IndexingProducts::etc/pipeline/product/relations/categories.yml
  attributes:
    pipeline: Pipeline\CreateRecord
    stages:
      name:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/name.yml
      sku:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/sku.yml
      image:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/image.yml
      price:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/price/configurable.yml
      url:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/url.yml
      inStock:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/in_stock.yml
      shortDescription:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/short_description.yml
      description:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/description.yml
      tags:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/tags.yml
      visibility:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/visibility.yml
      rating:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/rating.yml
      ratingCount:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/rating_count.yml
  groups:
    import: Klevu_IndexingProducts::etc/pipeline/product/groups/configurable.yml
