pipeline: Pipeline\CreateRecord
stages:
  id:
    pipeline: Stage\Extract
    args:
      extraction: currentProduct::getEntityId()
      transformations:
        - Prepend($currentParentProduct::getEntityId(), "-")
  type:
    pipeline: Stage\StaticValue
    args:
      value: "KLEVU_PRODUCT"
  relations:
    pipeline: Pipeline\CreateRecord
    stages:
      parentProduct:
        import: Klevu_IndexingProducts::etc/pipeline/product/relations/parent_product.yml
  attributes:
    pipeline: Pipeline\CreateRecord
    stages:
      sku:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/sku.yml
      image:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/image/variant.yml
      price:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/price.yml
      url:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/url/variant.yml
      inStock:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/in_stock/variant.yml
      shortDescription:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/short_description.yml
      description:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/description.yml
      rating:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/rating.yml
      ratingCount:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/rating_count.yml
      createdAt:
        import: Klevu_IndexingProducts::etc/pipeline/product/attributes/created_at.yml
  groups:
    import: Klevu_IndexingProducts::etc/pipeline/product/groups/default.yml
