stages:
  logStart:
    pipeline: Indexing\Stage\Log
    args:
      message: "Start Delete Products Pipeline"
  iterateIndexingRecords:
    pipeline: Pipeline\Iterate
    args:
      continueOnException: ~
    stages:
      processIndexingRecordStart:
        stages:
          registerIndexingRecordToContext:
            pipeline: Stage\RegisterContext
            args:
              contextKey: "currentIndexingRecord"
          registerActionToContext:
            stages:
              createAction:
                pipeline: Stage\StaticValue
                args:
                  value: "Delete"
              registerAction:
                pipeline: Stage\RegisterContext
                args:
                  contextKey: "currentAction"
          registerEntityTypeToContext:
            stages:
              createEntityType:
                pipeline: Stage\StaticValue
                args:
                  value: "KLEVU_PRODUCT"
              registerEntityType:
                pipeline: Stage\RegisterContext
                args:
                  contextKey: "currentEntityType"
      processProduct:
        pipeline: Pipeline\CreateRecord
        stages:
          -
            pipeline: Pipeline\Fallback
            stages:
              variantProduct: # Simple products belonging to configurable products
                stages:
                  - pipeline: Stage\Extract
                    args:
                      extraction: currentIndexingRecord::getParentId()
                  - pipeline: Stage\Validate
                    args:
                      validation: IsNotEmpty
                  - pipeline: Stage\Extract
                    args:
                      extraction: currentIndexingRecord::getEntityId()
                      transformations:
                        - Prepend($currentIndexingRecord::getParentId(), "-")
                        - Trim("-")
                        - Trim
              default:
                stages:
                  - pipeline: Stage\Extract
                    args:
                      extraction: currentIndexingRecord::getEntityId()
                      transformations: ToString
  processPayload:
    stages:
      mergeRecords:
        pipeline: Stage\Transform
        args:
          transformation: Flatten
      processRecords:
        # import: Klevu_Indexing::etc/pipeline/process-batch-delete-payload.yml
        import: ../../../module-m2-indexing/etc/pipeline/process-batch-delete-payload.yml
  logEnd:
    pipeline: Indexing\Stage\Log
    args:
      message: "End Delete Products Pipeline"
