pipeline: Pipeline\CreateRecord
stages:
  id:
    pipeline: Stage\Extract
    args:
      extraction: currentProduct::getEntityId()
      transformations:
        - Prepend($currentParentProduct::getEntityId(), "-")
  type:
    pipeline: Stage\StaticValue
    args:
      value: "KLEVU_PRODUCT"
  relations:
    pipeline: Pipeline\CreateRecord
    stages:
      parentProduct:
        import: relations/parent_product.yml
  attributes:
    pipeline: Pipeline\CreateRecord
    stages:
      sku:
        import: attributes/sku.yml
      images:
        import: attributes/images.yml
      prices:
        import: attributes/prices.yml
      url:
        import: attributes/url/variant.yml
      inStock:
        import: attributes/in_stock/variant.yml
      shortDescription:
        import: attributes/short_description.yml
      description:
        import: attributes/description.yml
      rating:
        import: attributes/rating.yml
      ratingCount:
        import: attributes/rating_count.yml
