pipeline: Pipeline\CreateRecord
stages:
  id:
    pipeline: Stage\Extract
    args:
      extraction: currentProduct::getEntityId()
      transformations: ToString
  type:
    pipeline: Stage\StaticValue
    args:
      value: "KLEVU_PRODUCT"
  relations:
    pipeline: Pipeline\CreateRecord
    stages:
      categories:
        import: relations/categories.yml
  attributes:
    pipeline: Pipeline\CreateRecord
    stages:
      name:
        import: attributes/name.yml
      sku:
        import: attributes/sku.yml
      images:
        import: attributes/images.yml
      prices:
        import: attributes/prices/grouped.yml
      url:
        import: attributes/url.yml
      inStock:
        import: attributes/in_stock.yml
      shortDescription:
        import: attributes/short_description.yml
      description:
        import: attributes/description.yml
      tags:
        import: attributes/tags.yml
      visibility:
        import: attributes/visibility.yml
      rating:
        import: attributes/rating.yml
      ratingCount:
        import: attributes/rating_count.yml
