stages:
  getCustomerGroups:
    pipeline: Stage\Extract
    args:
      extraction: store::getForCurrentStore().customer_groups # GET ALL CUSTOMER GROUPS FOR STORE
      transformations: ToString
  IterateCustomerGroups:
    pipeline: Pipeline\Iterate # LOOP OVER ALL CUSTOMER GROUPS
    args:
      continueOnException: ~
    stages:
      RegisterCurrentGroupId:
        pipeline: Stage\RegisterContext
        args:
          contextKey: "currentGroupId"
      CreateCurrentGroupKey:
        pipeline: Stage\Transform
        args:
          transformation: Prepend("grp_")
      RegisterCurrentGroupKey:
        pipeline: Stage\RegisterContext
        args:
          contextKey: "currentGroupKey"
      SetCustomerGroupIdOnProduct:
        pipeline: Stage\Extract
        args:
          extraction: currentProduct::
          transformations:
            - SetDataOnProduct("customer_group_id", $currentGroupId::)
      RegisterCurrentProductWithGroupId:
        pipeline: Stage\RegisterContext
        args:
          contextKey: "currentProduct"
      AddCustomerGroupDataToRecord:
        pipeline: Pipeline\CreateRecord
        stages:
          $currentGroupKey:::
            pipeline: Pipeline\CreateRecord
            stages:
              attributes:
                pipeline: Pipeline\CreateRecord
                stages:
                  price:
                    import: Klevu_IndexingProducts::etc/pipeline/product/groups/attributes/price/bundle.yml
  FormatCustomerGroups:
    pipeline: Stage\Transform
    args:
      transformation: Flatten(true)
