stages:
  getVariantUrl:
    pipeline: Pipeline\Fallback
    stages:
      getData:
        stages:
          extract:
            pipeline: Stage\Extract
            args:
              extraction: currentParentProduct::getProductUrl()
              transformations:
                - ToString
                - Trim
          validate:
            pipeline: Stage\Validate
            args:
              validation: IsNotEqualTo("", false)
          transform:
            pipeline: Stage\Transform
            args:
              transformation: Append()  # @TODO get configurable attributes and append to URL
